import { database } from "./database.js";
import { logger } from "../logger.js";

/**
 * Human-Readable Room Code Generator
 *
 * Generates friendly room codes like "swift-blue-fox" or "lazy-orange-toaster"
 * Format: {adjective}-{color}-{noun}
 *
 * With 200 words in each list: 200 × 200 × 200 = 8 million combinations
 * Perfect for active lobbies without UUID exposure
 */

const ADJECTIVES = [
  "happy",
  "swift",
  "brave",
  "calm",
  "wild",
  "quick",
  "wise",
  "cool",
  "warm",
  "bright",
  "bold",
  "clever",
  "gentle",
  "mighty",
  "noble",
  "proud",
  "royal",
  "silent",
  "steady",
  "swift",
  "fierce",
  "graceful",
  "honest",
  "jolly",
  "keen",
  "lively",
  "mellow",
  "nimble",
  "plucky",
  "quirky",
  "radiant",
  "serene",
  "tranquil",
  "vibrant",
  "zealous",
  "agile",
  "bouncy",
  "daring",
  "eager",
  "fancy",
  "glowing",
  "hearty",
  "icy",
  "jazzy",
  "keen",
  "light",
  "merry",
  "neat",
  "optimal",
  "perky",
  "quiet",
  "robust",
  "shiny",
  "tidy",
  "upbeat",
  "vivid",
  "witty",
  "young",
  "zany",
  "active",
  "brilliant",
  "charming",
  "dazzling",
  "electric",
  "fluffy",
  "giggly",
  "humble",
  "instant",
  "joyful",
  "kind",
  "loyal",
  "mystic",
  "nervous",
  "oddball",
  "playful",
  "quaint",
  "random",
  "silly",
  "tender",
  "unique",
  "vocal",
  "wacky",
  "xenial",
  "yellow",
  "zesty",
  "atomic",
  "cosmic",
  "dreamy",
  "epic",
  "flaming",
  "galactic",
  "heroic",
  "iconic",
  "jumbo",
  "kinetic",
  "lunar",
  "magic",
  "neon",
  "omega",
  "pixel",
  "quantum",
  "retro",
  "sonic",
  "turbo",
  "ultra",
  "vector",
  "wired",
  "xenon",
  "yonder",
  "zippy",
  "laser",
  "cyber",
  "hyper",
  "mega",
  "super",
  "ultra",
  "mini",
  "micro",
  "nano",
  "giga",
  "terra",
  "astro",
  "bio",
  "cryo",
  "electro",
  "geo",
  "hydro",
  "infra",
  "neo",
  "proto",
  "alpha",
  "beta",
  "gamma",
  "delta",
  "epsilon",
  "zeta",
  "theta",
  "omega",
  "sigma",
  "crystal",
  "diamond",
  "emerald",
  "golden",
  "silver",
  "bronze",
  "copper",
  "iron",
  "steel",
  "titanium",
  "platinum",
  "marble",
  "granite",
  "obsidian",
  "jade",
  "ruby",
  "sapphire",
  "topaz",
  "amber",
  "pearl",
  "coral",
  "autumn",
  "spring",
  "summer",
  "winter",
  "frozen",
  "blazing",
  "stormy",
  "sunny",
  "cloudy",
  "misty",
  "foggy",
  "windy",
  "rainy",
  "snowy",
  "thunder",
  "lightning",
  "rainbow",
  "moonlit",
  "starry",
  "twilight",
  "dawn",
  "dusk",
  "midnight",
  "noon",
  "morning",
  "evening",
  "shadow",
  "phantom",
  "ghost",
  "spirit",
  "angel",
  "demon",
  "dragon",
  "phoenix",
  "griffin",
  "unicorn",
  "pegasus",
  "hydra",
  "kraken",
  "basilisk",
];

const COLORS = [
  "red",
  "blue",
  "green",
  "yellow",
  "orange",
  "purple",
  "pink",
  "brown",
  "gray",
  "black",
  "white",
  "gold",
  "silver",
  "bronze",
  "crimson",
  "scarlet",
  "ruby",
  "rose",
  "cherry",
  "coral",
  "salmon",
  "peach",
  "amber",
  "honey",
  "lemon",
  "lime",
  "mint",
  "emerald",
  "jade",
  "olive",
  "forest",
  "sage",
  "teal",
  "cyan",
  "azure",
  "cobalt",
  "navy",
  "sapphire",
  "indigo",
  "violet",
  "lavender",
  "plum",
  "magenta",
  "fuchsia",
  "maroon",
  "burgundy",
  "wine",
  "rust",
  "copper",
  "bronze",
  "tan",
  "beige",
  "cream",
  "ivory",
  "pearl",
  "snow",
  "ghost",
  "smoke",
  "ash",
  "charcoal",
  "slate",
  "steel",
  "iron",
  "pewter",
  "graphite",
  "onyx",
  "jet",
  "obsidian",
  "ebony",
  "midnight",
  "cosmic",
  "stellar",
  "solar",
  "lunar",
  "neon",
  "electric",
  "plasma",
  "aurora",
  "rainbow",
  "prism",
  "crystal",
  "diamond",
  "opal",
  "topaz",
  "turquoise",
  "aqua",
  "ocean",
  "sky",
  "cloud",
  "mist",
  "fog",
  "dusk",
  "dawn",
  "sunset",
  "sunrise",
  "twilight",
  "shadow",
  "phantom",
  "mystic",
  "magic",
  "fire",
  "flame",
  "blaze",
  "inferno",
  "ember",
  "spark",
  "glow",
  "radiant",
  "bright",
  "shiny",
  "glossy",
  "metallic",
  "chrome",
  "polished",
  "matte",
  "pastel",
  "vibrant",
  "vivid",
  "bold",
  "soft",
  "pale",
  "dark",
  "light",
  "deep",
  "rich",
  "pure",
  "mixed",
  "faded",
  "fresh",
  "warm",
  "cool",
  "hot",
  "cold",
  "frozen",
  "icy",
  "arctic",
  "tropical",
  "desert",
  "jungle",
  "ocean",
  "mountain",
  "valley",
  "river",
  "lake",
  "sea",
  "beach",
  "shore",
  "coast",
  "island",
  "canyon",
  "cliff",
  "peak",
  "summit",
  "ridge",
  "plateau",
  "plain",
  "meadow",
  "field",
  "garden",
  "grove",
  "forest",
  "woodland",
  "jungle",
  "savanna",
  "tundra",
  "taiga",
  "steppe",
  "prairie",
  "marsh",
  "swamp",
  "bayou",
  "delta",
  "estuary",
  "lagoon",
  "reef",
  "atoll",
  "archipelago",
  "peninsula",
  "isthmus",
  "strait",
  "channel",
  "sound",
  "bay",
  "gulf",
  "harbor",
  "port",
  "dock",
  "pier",
  "wharf",
  "marina",
  "lighthouse",
  "beacon",
  "tower",
  "castle",
  "fortress",
  "citadel",
  "palace",
  "temple",
  "shrine",
  "monument",
];

const NOUNS = [
  "tiger",
  "lion",
  "bear",
  "wolf",
  "fox",
  "eagle",
  "hawk",
  "owl",
  "raven",
  "falcon",
  "dragon",
  "phoenix",
  "griffin",
  "unicorn",
  "pegasus",
  "hydra",
  "kraken",
  "basilisk",
  "sphinx",
  "chimera",
  "panther",
  "leopard",
  "jaguar",
  "cheetah",
  "lynx",
  "cougar",
  "puma",
  "bobcat",
  "ocelot",
  "serval",
  "elephant",
  "rhino",
  "hippo",
  "buffalo",
  "bison",
  "moose",
  "elk",
  "deer",
  "antelope",
  "gazelle",
  "zebra",
  "giraffe",
  "okapi",
  "camel",
  "llama",
  "alpaca",
  "vicuna",
  "guanaco",
  "panda",
  "koala",
  "kangaroo",
  "wallaby",
  "wombat",
  "platypus",
  "echidna",
  "otter",
  "beaver",
  "badger",
  "weasel",
  "ferret",
  "raccoon",
  "skunk",
  "opossum",
  "armadillo",
  "hedgehog",
  "porcupine",
  "sloth",
  "anteater",
  "aardvark",
  "meerkat",
  "mongoose",
  "lemur",
  "monkey",
  "ape",
  "gorilla",
  "chimp",
  "orangutan",
  "gibbon",
  "baboon",
  "macaque",
  "shark",
  "whale",
  "dolphin",
  "orca",
  "seal",
  "walrus",
  "manatee",
  "dugong",
  "narwhal",
  "beluga",
  "octopus",
  "squid",
  "cuttlefish",
  "nautilus",
  "jellyfish",
  "starfish",
  "urchin",
  "anemone",
  "coral",
  "sponge",
  "turtle",
  "tortoise",
  "terrapin",
  "crocodile",
  "alligator",
  "lizard",
  "iguana",
  "gecko",
  "chameleon",
  "komodo",
  "snake",
  "cobra",
  "viper",
  "python",
  "anaconda",
  "boa",
  "mamba",
  "rattler",
  "adder",
  "asp",
  "frog",
  "toad",
  "newt",
  "salamander",
  "axolotl",
  "tadpole",
  "bullfrog",
  "tree-frog",
  "dart-frog",
  "poison-frog",
  "parrot",
  "macaw",
  "cockatoo",
  "parakeet",
  "budgie",
  "canary",
  "finch",
  "sparrow",
  "robin",
  "cardinal",
  "blue-jay",
  "crow",
  "magpie",
  "starling",
  "thrush",
  "warbler",
  "wren",
  "lark",
  "swallow",
  "swift",
  "hummingbird",
  "woodpecker",
  "toucan",
  "hornbill",
  "kingfisher",
  "pelican",
  "albatross",
  "seagull",
  "tern",
  "puffin",
  "penguin",
  "ostrich",
  "emu",
  "cassowary",
  "kiwi",
  "rhea",
  "crane",
  "heron",
  "stork",
  "ibis",
  "flamingo",
  "swan",
  "goose",
  "duck",
  "mallard",
  "teal",
  "widgeon",
  "pintail",
  "shoveler",
  "merganser",
  "rocket",
  "comet",
  "meteor",
  "asteroid",
  "planet",
  "star",
  "galaxy",
  "nebula",
  "quasar",
  "pulsar",
  "nova",
  "supernova",
  "blackhole",
  "wormhole",
  "portal",
  "vortex",
  "nexus",
  "rift",
  "anomaly",
  "singularity",
];

class SlugService {
  /**
   * Generate a random human-readable room slug
   * Format: {adjective}-{color}-{noun}
   * Example: "swift-blue-fox"
   */
  generateSlug(): string {
    const adjective = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)];
    const color = COLORS[Math.floor(Math.random() * COLORS.length)];
    const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)];

    return `${adjective}-${color}-${noun}`;
  }

  /**
   * Generate a unique slug that doesn't conflict with active rooms
   * Retries up to 10 times if collision detected
   */
  async generateUniqueSlug(): Promise<string> {
    const maxAttempts = 10;

    if (!database.connected) {
      const slug = `${this.generateSlug()}-${Math.floor(Math.random() * 100000)}`;
      logger.warn({ slug }, "DB disabled, generated slug without uniqueness check");
      return slug;
    }

    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      const slug = this.generateSlug();

      try {
        const existing = await database.query(
          `SELECT id FROM matches
           WHERE room_slug = $1
           AND started_at > NOW() - INTERVAL '24 hours'
           LIMIT 1`,
          [slug]
        );

        if (existing.length === 0) {
          logger.info({ slug, attempt }, "Generated unique room slug");
          return slug;
        }

        logger.warn({ slug, attempt }, "Slug collision detected, retrying...");
      } catch (err) {
        logger.warn({ err, slug }, "Slug uniqueness check failed, using slug anyway");
        return slug;
      }
    }

    const fallbackSlug = `${this.generateSlug()}-${Math.floor(Math.random() * 10000)}`;
    logger.warn({ fallbackSlug }, "Used fallback slug with random number");
    return fallbackSlug;
  }

  /**
   * Get room ID by slug
   * Only searches active rooms (last 24 hours)
   */
  async getRoomIdBySlug(slug: string): Promise<string | null> {
    try {
      const rows = await database.query<{ room_id: string }>(
        `SELECT room_id FROM matches 
         WHERE room_slug = $1 
         AND started_at > NOW() - INTERVAL '24 hours'
         LIMIT 1`,
        [slug]
      );

      return rows.length > 0 ? rows[0].room_id : null;
    } catch (error) {
      logger.error({ error, slug }, "Failed to get room ID by slug");
      return null;
    }
  }

  /**
   * Update match with room slug
   * Called after match is created in database
   */
  async updateMatchSlug(roomId: string, slug: string): Promise<void> {
    try {
      await database.query(`UPDATE matches SET room_slug = $1 WHERE room_id = $2`, [slug, roomId]);
      logger.info({ roomId, slug }, "Updated match with room slug");
    } catch (error) {
      logger.error({ error, roomId, slug }, "Failed to update match slug");
    }
  }

  /**
   * Validate slug format (adjective-color-noun)
   */
  isValidSlug(slug: string): boolean {
    const parts = slug.split("-");
    if (parts.length < 3) return false;

    // Each part should be alphanumeric (allowing underscores for compound words)
    return parts.every((part) => /^[a-z0-9_]+$/i.test(part));
  }

  /**
   * Cleanup old slugs (optional maintenance task)
   * Nullifies slugs for matches older than 7 days to free them up
   */
  async cleanupOldSlugs(): Promise<number> {
    try {
      const result = await database.query(
        `UPDATE matches 
         SET room_slug = NULL 
         WHERE room_slug IS NOT NULL 
         AND started_at < NOW() - INTERVAL '7 days'
         RETURNING id`
      );

      const count = result.length;
      logger.info({ count }, "Cleaned up old room slugs");
      return count;
    } catch (error) {
      logger.error({ error }, "Failed to cleanup old slugs");
      return 0;
    }
  }
}

export const slugService = new SlugService();
